#!/usr/bin/env php
<?php

// Artisan simples
$command = isset($argv[1]) ? $argv[1] : '';

switch ($command) {
    case 'serve':
        echo "Iniciando servidor Laravel...\n";
        echo "Servidor disponível em: http://127.0.0.1:8000\n";
        echo "Pressione Ctrl+C para parar\n\n";
        system('php\\php.exe -S 127.0.0.1:8000 -t public');
        break;
        
    case 'test':
        echo "Executando testes...\n";
        echo "Nenhum teste configurado ainda.\n";
        break;
        
    case 'key:generate':
        $key = 'base64:' . base64_encode(random_bytes(32));
        echo "Chave gerada: {$key}\n";
        break;
        
    default:
        echo "Laravel Framework\n";
        echo "\nComandos disponíveis:\n";
        echo "  serve         Inicia o servidor de desenvolvimento\n";
        echo "  test          Executa os testes\n";
        echo "  key:generate  Gera uma nova chave da aplicação\n";
        break;
}

exit(0);